"""add checkout model

Revision ID: 788234ab8874
Revises: 
Create Date: 2020-02-21 15:46:52.303185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788234ab8874'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('bags', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkout_phone'), 'checkout', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkout_phone'), table_name='checkout')
    op.drop_table('checkout')
    # ### end Alembic commands ###
